export default [
  {
    artist: "By Builofy",
    creator: "kLZsoLwNRyaNEQJaDM66v9014Cw2",
    likes: 0,
    src: "breeze",
    title: "Daily mix 2",
    author: true,
    id: "-MlR1D8j8DkcpaXgUbnl",
    tracks: [
      { ref: "hibernation" },
      { ref: "rain" },
      { ref: "ruki" },
      { ref: "scream" },
      { ref: "sun" },
    ],
  },
  {
    artist: "By Builofy",
    creator: "kLZsoLwNRyaNEQJaDM66v9014Cw2",
    likes: 0,
    src: "chuska",
    title: "Daily mix 1",
    author: true,
    id: "-MlR1D8mWNhunjM4_kc9",
    tracks: [
      { ref: "dreams." },
      { ref: "federiko-fellini" },
      { ref: "hibernation" },
      { ref: "islam" },
      { ref: "naruto2" },
    ],
  },
  {
    artist: "By Mick Gordon",
    creator: "kLZsoLwNRyaNEQJaDM66v9014Cw2",
    likes: 0,
    src: "doom",
    title: "Daily mix 4",
    author: true,
    id: "-MlR1D8oqDsKfls3nx-G",
    tracks: [
      { ref: "naruto2." },
      { ref: "naruto3" },
      { ref: "naruto4" },
      { ref: "naruto5" },
      { ref: "naruto6" },
      { ref: "only" },
      { ref: "dreams." },
      { ref: "federiko-fellini" },
      { ref: "hibernation" },
      { ref: "islam" },
      { ref: "naruto2" },
      { ref: "rain" },
      { ref: "ruki" },
      { ref: "pamparam" },
      { ref: "scream" },
      { ref: "sun" },
    ],
  },
  {
    artist: "By Stepan",
    creator: "kLZsoLwNRyaNEQJaDM66v9014Cw2",
    likes: 0,
    src: "steampunk",
    title: "Daily mix 8",
    author: true,
    id: "-MlR1D8sx2zh8lZCxlz8",
    tracks: [
      { ref: "naruto2." },
      { ref: "naruto3" },
      { ref: "naruto4" },
      { ref: "naruto5" },
      { ref: "naruto6" },
      { ref: "only" },
    ],
  },
  {
    artist: "By Builofy",
    creator: "kLZsoLwNRyaNEQJaDM66v9014Cw2",
    likes: 0,
    src: "sun",
    title: "Daily mix 9",
    author: true,
    id: "-MlR1D8uP320zi-KhAQX",
    tracks: [
      { ref: "dreams." },
      { ref: "federiko-fellini" },
      { ref: "hibernation" },
      { ref: "islam" },
      { ref: "naruto2" },
    ],
  },
  {
    artist: "By Builofy",
    creator: "kLZsoLwNRyaNEQJaDM66v9014Cw2",
    likes: 0,
    src: "breeze",
    title: "Daily mix 2",
    author: true,
    id: "-MlR1D8vJ2lFVyhlYd2N",
    tracks: [
      { ref: "only" },
      { ref: "rain" },
      { ref: "ruki" },
      { ref: "pamparam" },
      { ref: "scream" },
      { ref: "sun" },
    ],
  },
];
